config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :projects

  resources :articles do
    resources :comments
  end

  get 'contact' => 'contacts#new'
  resources :contacts, only: [:new, :create]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments, dependent: :destroy
  validates :title, :body, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = policy_scope(Article).order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1
  def show
    set_comments
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    authorize @article
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
    authorize @article

    respond_to do |format|
      format.html do
        if @article.save
          redirect_to @article, notice: 'Article was successfully created.'
          current_user.articles << @article
        else
          render :new
        end
      end

      format.js do
        if @article.save
          current_user.articles << @article
          set_comments
        else
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /articles/1
  def update
    authorize @article

    respond_to do |format|
      format.html do
        if @article.update(article_params)
          redirect_to @article, notice: 'Article was successfully updated.'
        else
          render :edit
        end
      end

      format.js do
        @article.update(article_params)
        set_comments
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    respond_to do |format|
      format.html do
        redirect_to articles_url, notice: 'Article was successfully destroyed.'
      end

      format.js do
        # render layout: false
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def set_comments
    @comment = @article.comments.build
    @comments = policy_scope(@article.comments)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :body, :image_url, :page, (:published if current_user.role == "editor"))
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @article.title %></h1>

<% unless @article.published? %>
  <h5>-- UNPUBLISHED --</h5>
<% end %>

<p id="author">
  <em><%= @article.author.email %></em>
</p>

<p>
  <%= image_tag @article.image_url %>
</p>

<p>
  <%= markdown(@article.body) %>
</p>

<div class="comments">
  <hr>
  <%= render template: "comments/index" %>
  <%= render template: "comments/new" %>
</div>

<div class="article_links">
  <hr>
  <% if policy(@article).edit? || policy(@article).authors_own? %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
  <% end %>
  <% if policy(@article).destroy? %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'All Articles', articles_path %>
</div>

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
  <div class="article" id="<%= dom_id article %>">
    <h1><%= link_to article.title, article, remote: true %></h1>
    <p><%= markdown(article.body) %></p>

    <div class="article_links">
      <% if policy(article).update? %>
        <%= link_to 'Edit', edit_article_path(article), remote: true %>
      <% end %>
      <% if policy(article).destroy? %>
        | <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
      <% end %>
    </div>

    <hr>
  </div>
<% end %>

<%= will_paginate @articles %>

app/views/articles/_form.html.erb
<%= form_for @article, remote: true do |f| %>
  <h1><%= @article.new_record? ? "New" : "Edit" %> Article</h1>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <% if policy(@article).publish? %>
    <div class="field">
      <%= f.label :published, title: "Is this article published?", data: { tooltip: true } %>
      <%= f.check_box :published %>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
    | <%= link_to 'All Articles', articles_path %>
  </div>
<% end %>

app/views/articles/create.js.erb
$('#new_article').hide().after('<%= j render("article") %>');
history.pushState(null, "", "<%= j article_url(@article) %>");

app/views/articles/destroy.js.erb
$('#<%= dom_id @article %>').fadeOut();

app/views/articles/edit.html.erb
<%= render 'form' %>

<div id="edit_links">
  <%= link_to 'Show', @article %> |
  <% if policy(@article).destroy? %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/edit.js.erb
$('#articles_container').hide().after('<%= j render("form") %>');
$('#new_link').hide();
history.pushState(null, "", "<%= j edit_article_url(@article) %>");

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div id="articles_container">
  <%= render 'articles' %>
  <%# render article, locals: { articles: @articles } %>
</div>

<br>

<% if policy(@articles).create? %>
  <%= link_to 'New Article', new_article_path, id: :new_link, remote: true %>
<% end %>

app/views/articles/index.js.erb
$('#articles_container').html('<%= j render "articles" %>');

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/new.js.erb
$('#articles_container').hide();
if ($('#new_article').length) {
  $('#new_article').replaceWith('<%= j render("form") %>');
} else {
  $('#new_link').hide().after('<%= j render("form") %>');
}
history.pushState(null, "", "<%= j new_article_url %>");

app/views/articles/show.html.erb
<%= render 'article' %>

app/views/articles/show.js.erb
$('#articles_container').hide().after('<%= j render("article") %>');
$('#new_link').hide();
history.pushState(null, "", "<%= j article_url(@article) %>");

app/views/articles/update.js.erb
$('#edit_article_<%= @article.id %>').replaceWith('<%= j render(@article) %>');
$('#edit_links').remove();
history.pushState(null, "", "<%= j article_url(@article) %>");