config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :projects

  resources :articles do
    resources :comments
  end

  get 'contact' => 'contacts#new'
  resources :contacts, only: [:new, :create]

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }
  mount_uploader :image, ScreenshotUploader

  # after_save :enqueue_image

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present? && !image_processed
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id, key)
      project = Project.find(id)
      project.key = key
      project.remote_image_url = project.image.direct_fog_url(with_path: true)
      project.update_column(:image_processed, true)
      project.save!
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
    @uploader = Project.new.image
    @uploader.success_action_redirect = new_project_url
  end

  def new
    @project = Project.new(key: params[:key])
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    authorize @project

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:error] = "Project could not be saved."
      render :new
    end
  end

  def show
    if request.path != project_path(@project)
      redirect_to @project, status: 301
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project

    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @project

    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  private

  def project_params
    params.require(:project).permit(:name, :slug, :technologies_used, :image, :key)
  end

  def set_project
    @project = Project.friendly.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {multipart: true}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @project.image_url.present? || params.has_key?(:key) %>
    <%= f.hidden_field :key %>

    <p>File: <%= @project.image_name %></p>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br>
    <%= f.text_area :technologies_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<%= link_to "Cancel", :back %>

app/views/projects/index.html.erb
<h2>Recent Projects</h2>
<% @projects.each do |project| %>
  <div class="project" id="<%= dom_id(project) %>">
    <h3><%= link_to project.name, project %></h3>
    <p><%= project.technologies_used %></p>
    <div class="nav">
      <% if policy(project).update? %>
        <%= link_to 'Edit', edit_project_path(project) %>
      <% end %>
      <% if policy(project).destroy? %>
        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
<% end %>
<br>
<%# link_to 'New Project', new_project_path %>

<% if policy(@projects).create? %>
  <%= direct_upload_form_for @uploader do |f| %>
    <p><%= f.file_field :image %></p>
    <p><%= f.submit "Upload Image" %></p>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>
  <% if @project.image_processed? %>
    <%= image_tag @project.image_url(:thumb).to_s %>
  <% elsif @project.image_url %>
    <em>Processing...</em>
  <% end %>
</p>
<p>Technologies used: <%= @project.technologies_used %></p>
<br>
<div class="nav">
  <% if policy(@project).update? %>
    <%= link_to 'Edit', edit_project_path(@project) %>
    <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>